name: C/C++ CI

on:
  push:
    branches: [ master_sync ]
  pull_request:
    branches: [ master_sync ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: befor install
      run: sudo apt-get -qq install libmysql++-dev libace-dev
    - name: deps
      run: sudo apt-get -qq install cmake build-essential cppcheck git make binutils-dev libiberty-dev openssl libssl-dev
    - name: make 
      run: mkdir build
    - name: cd build
      run: cd build
    - name: cmake
      run: cmake .. -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DSERVERS=1 -DTOOLS=1 -DSCRIPTS=1 -DWITH_DOCS=1 -DWITH_WARNINGS=0 -DELUNA=0 -DWITH_COREDEBUG=0
    - name: make 
      run: make -j2
    - name: make install
      run: make install
